name: map
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  yandex_mapkit: ^4.1.0
  geolocator: ^14.0.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.6
  get_it: ^7.2.0
  equatable: ^2.0.5
  connectivity_plus: ^6.1.4
  network_info_plus: ^6.1.4
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.4.6


flutter:


  uses-material-design: true


  assets:
     - assets/images/car.png



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

